package com.example.careiroapp.bag.ui

import android.graphics.Bitmap
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.res.colorResource
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.careiroapp.R
import com.example.careiroapp.common.montserratBoldFontFamily
import com.example.careiroapp.common.montserratRegularFontFamily
import com.google.zxing.BarcodeFormat
import com.google.zxing.qrcode.QRCodeWriter
import androidx.core.graphics.createBitmap
import androidx.core.graphics.set

@Composable
fun CheckoutFinalStepView(
    padding: PaddingValues,
    pixPayload: String? = null
) {

    var qrCodeGenerated by remember { mutableStateOf<Bitmap?>(generateQRCode(pixPayload)) }

    Column(
        modifier = Modifier
            .padding(padding)
            .padding(horizontal = 15.dp, vertical = 24.dp)
            .fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text(
            "Pedido feito!",
            style = TextStyle(
                fontSize = 18.sp,
                fontFamily = montserratBoldFontFamily,
                color = colorResource(R.color.dark_green)
            )
        )
        Spacer(modifier = Modifier.height(16.dp))
        Text(
            "Faça o pagamento PIX para confirmar o pedido:",
            style = TextStyle(
                fontSize = 14.sp,
                fontFamily = montserratRegularFontFamily,
                color = colorResource(R.color.dark_green)
            )
        )
        Spacer(modifier = Modifier.height(19.dp))
        qrCodeGenerated?.let {
            Image(
                bitmap = qrCodeGenerated!!.asImageBitmap(),
                contentDescription = null,
                modifier = Modifier.size(300.dp)
            )
        }
    }
}

fun generateQRCode(text: String?): Bitmap {
    val matrix = QRCodeWriter().encode(text, BarcodeFormat.QR_CODE, 300, 300)
    val w = matrix.height
    val h = matrix.width

    val bitmap = createBitmap(w, h, Bitmap.Config.RGB_565)

    for (y in 0..< h) {
        for (x in 0..< w) {
            bitmap[x, y] = if (matrix.get(x, y))
                android.graphics.Color.BLACK else {
                android.graphics.Color.WHITE
            }
        }
    }
    return bitmap
}

@Preview(showBackground = true)
@Composable
private fun CheckoutFinalStepViewPreview() {
    CheckoutFinalStepView(
        padding = PaddingValues(),
        pixPayload = "google.com"
    )
}