package com.example.careiroapp.bag.ui

import android.content.ClipData
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Color
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.platform.ClipEntry
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.res.colorResource
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.graphics.createBitmap
import androidx.core.graphics.set
import coil3.compose.rememberAsyncImagePainter
import com.airbnb.lottie.compose.LottieAnimation
import com.airbnb.lottie.compose.LottieCompositionSpec
import com.airbnb.lottie.compose.rememberLottieComposition
import com.example.careiroapp.R
import com.example.careiroapp.bag.ui.viewmodel.OrderModel
import com.example.careiroapp.bag.ui.viewmodel.PaymentType
import com.example.careiroapp.common.components.buttons.AppButton
import com.example.careiroapp.common.montserratBoldFontFamily
import com.example.careiroapp.common.montserratRegularFontFamily
import com.google.zxing.BarcodeFormat
import com.google.zxing.qrcode.QRCodeWriter
import kotlin.io.encoding.Base64

@Composable
fun CheckoutFinalStepView(
    padding: PaddingValues,
    orderData: OrderModel,
) {

    val qrColor = colorResource(R.color.black).toArgb()
    val bgColor = colorResource(R.color.light_background).toArgb()

    val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.wallet_animation))

    val clipboardManager = LocalClipboardManager.current

    val qrCodeGenerated by remember(orderData.pixPayload) {
        mutableStateOf(
            if (orderData.paymentType == PaymentType.PIX && !orderData.pixPayload.isNullOrEmpty()) {
                generateQRCode(orderData.pixPayload, qrColor, bgColor)
            } else {
                null
            }
        )
    }

    Column(
        modifier = Modifier
            .padding(padding)
            .padding(horizontal = 15.dp, vertical = 24.dp)
            .fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text(
            "Pedido feito!",
            style = TextStyle(
                fontSize = 18.sp,
                fontFamily = montserratBoldFontFamily,
                color = colorResource(R.color.dark_green)
            )
        )
        Spacer(modifier = Modifier.height(16.dp))
        when (orderData.paymentType) {
            PaymentType.PIX -> {
                Text(
                    "Faça o pagamento PIX para confirmar o pedido:",
                    style = TextStyle(
                        fontSize = 14.sp,
                        fontFamily = montserratRegularFontFamily,
                        color = colorResource(R.color.dark_green)
                    )
                )
                Spacer(modifier = Modifier.height(19.dp))
                Image(
                    painter = rememberAsyncImagePainter(orderData.pixQrCode),
                    contentDescription = null,
                    modifier = Modifier.size(300.dp)
                )
                Spacer(modifier = Modifier.height(24.dp))
                AppButton(
                    text = "Copiar codigo PIX",
                    modifier = Modifier,
                    onClick = {
                        val clipData = ClipData.newPlainText("plain text", orderData.pixPayload)
                        val clipEntry = ClipEntry(clipData)
                        clipboardManager.setClip(clipEntry)
                    },
                    icon = painterResource(R.drawable.copy),
                    containerColor = colorResource(R.color.dark_green)
                )
            }
            PaymentType.DINHEIRO -> {
                Text(
                    "Seu pedido foi registrado com sucesso. Por favor, prepare o valor em dinheiro e pague diretamente na retirada.",
                    style = TextStyle(
                        fontSize = 14.sp,
                        fontFamily = montserratRegularFontFamily,
                        textAlign = TextAlign.Center,
                        color = colorResource(R.color.dark_green)
                    )
                )
                LottieAnimation(composition)
                Spacer(modifier = Modifier.height(16.dp))
                Text(
                    "Valor a pagar em dinheiro:",
                    style = TextStyle(
                        fontSize = 14.sp,
                        fontFamily = montserratRegularFontFamily,
                        color = colorResource(R.color.dark_gray)
                    )
                )
                Spacer(modifier = Modifier.height(8.dp))
                Text(
                    "R$ ${orderData.totalValue}",
                    style = TextStyle(
                        fontSize = 24.sp,
                        fontFamily = montserratBoldFontFamily,
                        color = colorResource(R.color.dark_green)
                    )
                )
            }

            else -> {}
        }
    }
}

fun generateQRCode(
    text: String?,
    onColor: Int = Color.BLACK,
    offColor: Int = Color.WHITE
): Bitmap? {
    if (text.isNullOrEmpty()) return null

    return try {
        val matrix = QRCodeWriter().encode(text, BarcodeFormat.QR_CODE, 300, 300)
        val w = matrix.height
        val h = matrix.width

        val bitmap = createBitmap(w, h, Bitmap.Config.RGB_565)

        for (y in 0..<h) {
            for (x in 0..<w) {
                bitmap[x, y] = if (matrix.get(x, y))
                    onColor else {
                    offColor
                }
            }
        }
        bitmap
    } catch (e: Exception) {
        null
    }
}

@Preview(showBackground = true)
@Composable
private fun CheckoutFinalStepViewPixPreview() {

    val order = OrderModel(
        paymentType = PaymentType.PIX
    )

    CheckoutFinalStepView(
        padding = PaddingValues(),
        orderData = order,
    )
}

@Preview(showBackground = true)
@Composable
private fun CheckoutFinalStepViewDinheiroPreview() {

    val order = OrderModel(
        paymentType = PaymentType.DINHEIRO
    )

    CheckoutFinalStepView(
        padding = PaddingValues(),
        orderData = order,
    )
}